"""
License Manager for POS V3 (On-Premises)
=========================================
Provides:
  - Hardware fingerprint generation (CPU, MAC, disk serial)
  - RSA-signed license key verification (company + hardware bound, expiry)
  - Periodic online heartbeat with offline grace period
  - Fernet-encrypted backup helper
"""

import os
import json
import base64
import hashlib
import platform
import subprocess
import threading
import time
import logging
from datetime import datetime, timedelta

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding as asym_padding
    from cryptography.hazmat.backends import default_backend
    from cryptography.fernet import Fernet, InvalidToken
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    CRYPTO_AVAILABLE = True
except ImportError:
    CRYPTO_AVAILABLE = False

logger = logging.getLogger(__name__)

# ─── Vendor RSA Public Key (2048-bit) ────────────────────────────────────────
# Generated by keygen.py.  Override via VENDOR_PUBLIC_KEY_PEM env-var if needed.
_EMBEDDED_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArNWOMK9FXg/izhUi3hMP
6DHnV8kdOJnZMKux5aAu1DdAmIVCaWdqiaqdnF8tJQAx9GLlFPnxCiRXOHgRK5uF
RviSB6MNozCDvPb4TXqjlUQU7FEybZBkT37XdcacbdOix/LCwUmLQeOIP6O6pSe8
TDxwsggSQsXLSv4NPMKEGtJOOT2f18s62IZxZmw+SohEudE88R+DHrZDX/J4HYQm
GxN9z4ypPj/ZSYDYhDNHt78VBC6OaUmoK2MxyekyT14R9Tk1qOLzFFKt60mi4eAz
rCcZXPIhORv1tmk6XNloWMuC65RCR53Yjks9IzoF+5/Gx7bVl6GkYqIfqSTfBX1w
YwIDAQAB
-----END PUBLIC KEY-----"""
VENDOR_PUBLIC_KEY_PEM = os.environ.get("VENDOR_PUBLIC_KEY_PEM", _EMBEDDED_PUBLIC_KEY)

# ─── Configuration ────────────────────────────────────────────────────────────
LICENSE_FILE = os.environ.get("LICENSE_FILE", "license.key")
LICENSE_SERVER_URL = os.environ.get("LICENSE_SERVER_URL", "").strip()
HEARTBEAT_INTERVAL_SEC = int(os.environ.get("LICENSE_HEARTBEAT_INTERVAL", "14400"))  # 4 h
OFFLINE_GRACE_HOURS = int(os.environ.get("LICENSE_OFFLINE_GRACE_HOURS", "72"))       # 3 d

_license_cache: dict | None = None
_last_heartbeat: datetime | None = None
_license_lock = threading.Lock()


# ─── Hardware Fingerprint ─────────────────────────────────────────────────────

def get_hardware_fingerprint() -> str:
    """Return a stable 32-char SHA-256 fingerprint of this machine's hardware."""
    components: list[str] = []

    # MAC address
    try:
        import uuid
        node = uuid.getnode()
        mac = ":".join(f"{(node >> i) & 0xff:02x}" for i in range(40, -1, -8))
        components.append(f"mac:{mac}")
    except Exception:
        pass

    # CPU identifier (Windows: WMIC; Linux: /proc/cpuinfo)
    try:
        if platform.system() == "Windows":
            out = subprocess.check_output(
                ["wmic", "cpu", "get", "ProcessorId"],
                stderr=subprocess.DEVNULL, timeout=5
            ).decode().strip().splitlines()
            cpu_id = next((ln.strip() for ln in out if ln.strip() and ln.strip() != "ProcessorId"), "")
            if cpu_id:
                components.append(f"cpu:{cpu_id}")
        else:
            with open("/proc/cpuinfo") as fh:
                for line in fh:
                    if "serial" in line.lower():
                        components.append(f"cpu:{line.split(':')[-1].strip()}")
                        break
    except Exception:
        pass

    # Disk serial number (Windows only)
    try:
        if platform.system() == "Windows":
            out = subprocess.check_output(
                ["wmic", "diskdrive", "get", "SerialNumber"],
                stderr=subprocess.DEVNULL, timeout=5
            ).decode().strip().splitlines()
            disk_id = next((ln.strip() for ln in out if ln.strip() and ln.strip() != "SerialNumber"), "")
            if disk_id:
                components.append(f"disk:{disk_id}")
    except Exception:
        pass

    # Hostname as stable fallback
    components.append(f"host:{platform.node()}")

    raw = "|".join(components)
    return hashlib.sha256(raw.encode()).hexdigest()[:32]


# ─── License Verification ─────────────────────────────────────────────────────

def _b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def _b64url_decode(s: str) -> bytes:
    padding = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + padding)


def verify_license(license_path: str | None = None) -> dict:
    """
    Load and cryptographically verify a license file.

    Returns the decoded payload dict on success.
    Raises LicenseError on any failure (file missing, bad signature,
    expiry exceeded, hardware mismatch).
    """
    if not CRYPTO_AVAILABLE:
        raise LicenseError("'cryptography' package is required for license validation")

    if not VENDOR_PUBLIC_KEY_PEM.strip():
        raise LicenseError(
            "VENDOR_PUBLIC_KEY_PEM is not configured. "
            "Set it via the environment variable or embed it in license_manager.py."
        )

    path = license_path or LICENSE_FILE

    # Support Azure Blob SAS URLs or any HTTPS-hosted license
    if path.startswith("http://") or path.startswith("https://"):
        try:
            import urllib.request as _urllib_request
            with _urllib_request.urlopen(path, timeout=10) as resp:
                content = resp.read().decode().strip()
        except Exception as exc:
            raise LicenseError(
                f"Could not fetch license from URL: {exc}. "
                "Check LICENSE_FILE URL and network connectivity."
            ) from exc
    else:
        if not os.path.exists(path):
            raise LicenseError(f"License file not found: {path}")
        with open(path, "r") as fh:
            content = fh.read().strip()

    # Format: <base64url-payload>.<base64url-signature>
    parts = content.split(".")
    if len(parts) != 2:
        raise LicenseError("Invalid license format (expected payload.signature)")

    payload_b64, sig_b64 = parts
    try:
        payload_bytes = _b64url_decode(payload_b64)
        sig_bytes = _b64url_decode(sig_b64)
        payload = json.loads(payload_bytes.decode())
    except Exception as exc:
        raise LicenseError(f"License could not be decoded: {exc}") from exc

    # Verify RSA-PKCS1v15-SHA256 signature
    try:
        from cryptography.hazmat.primitives.serialization import load_pem_public_key
        pub_key = load_pem_public_key(
            VENDOR_PUBLIC_KEY_PEM.strip().encode(),
            backend=default_backend()
        )
        pub_key.verify(sig_bytes, payload_bytes, asym_padding.PKCS1v15(), hashes.SHA256())
    except LicenseError:
        raise
    except Exception as exc:
        raise LicenseError(f"License signature is invalid: {exc}") from exc

    # Expiry check
    expiry_str = payload.get("expiry", "")
    try:
        expiry_date = datetime.strptime(expiry_str, "%Y-%m-%d").date()
    except ValueError as exc:
        raise LicenseError("License contains an invalid expiry date") from exc

    if datetime.utcnow().date() > expiry_date:
        raise LicenseError(
            f"License expired on {expiry_str}. "
            "Contact your vendor to renew."
        )

    # Hardware fingerprint binding
    licensed_fp = payload.get("hardware_fp", "")
    if licensed_fp:
        current_fp = get_hardware_fingerprint()
        if current_fp != licensed_fp:
            raise LicenseError(
                "This license is not valid for the current hardware. "
                "Contact your vendor to re-activate."
            )

    return payload


def check_license() -> dict:
    """Return cached verified license payload. Raises LicenseError if invalid."""
    global _license_cache
    with _license_lock:
        if _license_cache is None:
            _license_cache = verify_license()
        return _license_cache


def invalidate_license_cache() -> None:
    """Force re-verification on next check_license() call."""
    global _license_cache
    with _license_lock:
        _license_cache = None


# ─── Online Heartbeat ─────────────────────────────────────────────────────────

def _send_heartbeat(payload: dict) -> bool:
    """
    POST a heartbeat to the license server.
    Returns True if the server confirms the license is still valid.
    Returns False on network failure (offline grace applies).
    Raises LicenseError if the server explicitly rejects the license.
    """
    global _last_heartbeat

    if not LICENSE_SERVER_URL:
        _last_heartbeat = datetime.utcnow()
        return True  # offline / no server configured — always passes

    import urllib.request
    import urllib.error

    data = json.dumps({
        "license_id": payload.get("license_id", ""),
        "company_id": payload.get("company_id", ""),
        "hardware_fp": get_hardware_fingerprint(),
    }).encode()

    try:
        req = urllib.request.Request(
            f"{LICENSE_SERVER_URL.rstrip('/')}/heartbeat",
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode())

        if result.get("valid"):
            _last_heartbeat = datetime.utcnow()
            return True
        raise LicenseError(
            f"License server rejected activation: {result.get('message', 'unknown reason')}"
        )

    except LicenseError:
        raise
    except Exception as exc:
        logger.warning("License heartbeat network failure: %s", exc)
        return False


def _heartbeat_worker(on_failure=None) -> None:
    """Background thread: send periodic heartbeats, enforce offline grace."""
    global _last_heartbeat

    while True:
        time.sleep(HEARTBEAT_INTERVAL_SEC)
        try:
            payload = check_license()
            reachable = _send_heartbeat(payload)

            if not reachable and _last_heartbeat is not None:
                grace_deadline = _last_heartbeat + timedelta(hours=OFFLINE_GRACE_HOURS)
                if datetime.utcnow() > grace_deadline:
                    msg = (
                        f"License server unreachable for >{OFFLINE_GRACE_HOURS}h. "
                        "Application access suspended until connectivity is restored."
                    )
                    logger.critical(msg)
                    invalidate_license_cache()
                    if on_failure:
                        on_failure(msg)
        except LicenseError as exc:
            logger.critical("License heartbeat error: %s", exc)
            invalidate_license_cache()
            if on_failure:
                on_failure(str(exc))


def start_heartbeat_thread(on_failure=None) -> threading.Thread:
    """
    Start the background heartbeat thread.

    Args:
        on_failure: optional callable(message: str) invoked when license
                    becomes invalid during a heartbeat.
    Returns the daemon thread.
    """
    # Perform an immediate first heartbeat synchronously so startup fails fast.
    try:
        payload = check_license()
        _send_heartbeat(payload)
    except LicenseError:
        raise

    t = threading.Thread(
        target=_heartbeat_worker,
        kwargs={"on_failure": on_failure},
        daemon=True,
        name="license-heartbeat",
    )
    t.start()
    return t


# ─── Encrypted Backup Helpers ─────────────────────────────────────────────────

_BACKUP_SALT = b"pos_v3_backup_salt_v1_mauritius"


def _derive_fernet_key(passphrase: str) -> bytes:
    """Derive a URL-safe base64-encoded Fernet key from *passphrase*."""
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=_BACKUP_SALT,
        iterations=260_000,
        backend=default_backend(),
    )
    return base64.urlsafe_b64encode(kdf.derive(passphrase.encode()))


def encrypt_backup(src_path: str, dest_path: str, passphrase: str) -> None:
    """Encrypt *src_path* with Fernet and write to *dest_path* (.enc)."""
    if not CRYPTO_AVAILABLE:
        raise RuntimeError("'cryptography' package required for backup encryption")
    f = Fernet(_derive_fernet_key(passphrase))
    with open(src_path, "rb") as fh:
        plaintext = fh.read()
    with open(dest_path, "wb") as fh:
        fh.write(f.encrypt(plaintext))


def decrypt_backup(src_path: str, dest_path: str, passphrase: str) -> None:
    """Decrypt *src_path* (written by encrypt_backup) to *dest_path*."""
    if not CRYPTO_AVAILABLE:
        raise RuntimeError("'cryptography' package required for backup decryption")
    f = Fernet(_derive_fernet_key(passphrase))
    with open(src_path, "rb") as fh:
        ciphertext = fh.read()
    try:
        plaintext = f.decrypt(ciphertext)
    except InvalidToken as exc:
        raise ValueError("Backup decryption failed — wrong passphrase or corrupted file") from exc
    with open(dest_path, "wb") as fh:
        fh.write(plaintext)


# ─── Exception ────────────────────────────────────────────────────────────────

class LicenseError(Exception):
    """Raised for any license validation failure."""
